### ISSUE TITLE
Support to get the certificate URL only after order finalization status is valid

### ISSUE THREAD

**Issue by iulianbarbu** [InstantDomain/instant-acme#14]
Hey, run into some issue with the certificates URL retrieval, after an order finalization. I believe it would be helpful for `instant-acme` Order struct to have an implementation for `poll_and_finalize`, as in: https://github.com/certbot/certbot/blob/7a6752a68ed77e73c2b29ab20d3ca8927f4fa7b0/acme/acme/client.py#L240 when finalizing an order, upon checking the certificate URL. This is needed because of https://github.com/letsencrypt/pebble/issues/402 basically. If this makes sense, I would be happy to provide support for it.

**Comment by djc** [comment]
Thanks for reporting! Happy to get feedback on the proposed change.

**Comment by iulianbarbu** [comment]
Hey @djc . The PR looks great. Can you publish the latest version to `crates.io` as well? Seems like the latest version published is 0.1.3.

**Comment by iulianbarbu** [comment]
I appreciate it! Thanks a lot.
